### ISSUE TITLE
Storybook alternatives

### ISSUE THREAD

**Issue by runoncedev** [oncet/super-spork#1]
Should we use a doc tool like Storybook, Pattern Lab or Zero Height? Or just build a website using something like Next.js?

**Comment by runoncedev** [comment]
* Zero Height seems to be a paid service.
* Pattern Lab seems to have very little community.
* And we are tired of Storybook.

So something like Next.js should be a better fit.

**Comment by runoncedev** [comment]
A few alternatives to Next.js and Lit:

Stencil:

* SSG for web components
* It has auto-generated components documentation
* Uses JSX
* Provides out wrappers for various frameworks (including React but only v16)
* Backed by Ionic

Mitosis:

* A framework to write components and transpile them to multiple differente formats (React, Lit, web components, etc)
* Can't find to which React version it transpiles
* Supported by Builder.io, creators of [figma-html](https://github.com/builderio/figma-html) and [Qwik](https://qwik.builder.io/)
* Uses JSX

Lit:
* Backed by Google

**Comment by matidelmar** [comment]
Lit:
- Backed by Google and its been used by google team internally 
- SSR is still in WIP but its a core functionality that Lit team wants to add -> https://github.com/lit/lit/tree/main/packages/labs/ssr
- Lightweight, 2.8k minified and compressed
- It has a growing community, extensive docs and tutorials

**Comment by runoncedev** [comment]
After some though looks like we are going to go with Lit and Next.js in 2 separated repos:

* A component library published on npm
* An Next.js app for documentation
